apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gbw2jo7mv-nodejs
  janus-idp.io/tekton: gbw2jo7mv-nodejs
  backstage.io/kubernetes-id: gbw2jo7mv-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gbw2jo7mv-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
