apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gbw2jo7mv-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gbw2jo7mv-nodejs 
  name: gbw2jo7mv-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: gbw2jo7mv-nodejs 
